### ISSUE TITLE
llvm-mt retuns 'error: no libxml2'

### ISSUE THREAD

**Issue by xoviat** [conda-forge/llvmdev-feedstock#117]
libxml2 appears to be installed on my local computer.

```
miniconda3\Library\bin\llvm-mt.exe /nologo /manifest CMakeFiles\CMakeTmp\CMakeFiles\cmTC_17307.dir/intermediate.manifest /out:CMakeFiles\cmTC_17307.dir/embed.manifest /notify_update
llvm-mt: ignoring unsupported 'notify_update' option
llvm-mt: error: no libxml2
```

**Comment by isuruf** [comment]
We've turned off libxml2 support in https://github.com/conda-forge/llvmdev-feedstock/blob/master/recipe/bld.bat#L25
Can you send a PR to turn it on?

**Comment by isuruf** [comment]
Yeah, cmake was probably using `mt` from the visual studio installation before.
