### ISSUE TITLE
Cling feature behavior

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/llvmdev-feedstock#12]
It seems that the behavior of build features is not deterministic, from one execution to another, I get a different version of clangdev.

![image](https://cloud.githubusercontent.com/assets/2397974/22896278/c7c84cb0-f21f-11e6-9583-9eb27a0235c6.png)

Ping @mcg1969 - if you have a minute to discuss the behavior of cling build features it would be great!

**Comment by mcg1969** [comment]
Hmm, I'm not sure I understand what's going on. Are you absolutely sure the `cling-patches` package as the `track_features` value in its metadata, and that the `cling` patches have the proper `features` entry? If so, it should always be preferred over the defaults version. This might very well be a conda bug.

The symptoms _suggest_ that one or the other of the features/track_features pair is missing, which means that conda has no reason to prefer one package over the other. And in that case, conda is indeed not deterministic.

**Comment by SylvainCorlay** [comment]
@mcg1969 if you guys at a little bit of time this week to answer questions about build features that would be awsome.

**Comment by mcg1969** [comment]
Honestly, I don't know if I do. I'd prefer it if we can get a reproducible issue into the conda issue tracker. What I'm seeing here is either a problem with the metadata or a bug in conda.

**Comment by mcg1969** [comment]
Again, the behavior in that screen shot is _not_ what I would expect. It should _always_ prefer the feature packages if you install the corresponding metapackage.

**Comment by mcg1969** [comment]
I actually do have time next week, my client pressures are lower then. But if I can take a look at this asynchronously I ought to have a resolution sooner.

**Comment by SylvainCorlay** [comment]
Thanks!

I have done a lot of work for the packaging of cling and this surprising behavior is pretty much the last blocker. 

Do you think specifying the build string in the dependencies of string to get the right version would be a good way to go forward in the mean time
