### ISSUE TITLE
clang-cl broken on Windows

### ISSUE THREAD

**Issue by bluescarni** [conda-forge/llvmdev-feedstock#120]
It seems like #118 might have broken something on Windows. Since today, the CI pipeline of one of my projects on Windows is failing when using ``clang-cl``:

https://ci.appveyor.com/project/bluescarni/heyoka/builds/38634320#L324

The last working build was yesterday:

https://ci.appveyor.com/project/bluescarni/heyoka/builds/38612193

**Comment by isuruf** [comment]
> It seems like #118 might have broken something on Windows.

Nope. It was trying to fix this issue, but it may not have worked. To fix this, we might have to do `-DLLVM_ENABLE_LIBXML2=FORCE_ON` to see if it worked.

Issue is with new cmake version which started using `llvm-mt` instead of `mt` from the system.

**Comment by bluescarni** [comment]
Ah ok I see, thanks for the clarification!
