### ISSUE TITLE
Fix to random feature selection issue

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/llvmdev-feedstock#14]
@ocefpaf @inducer 

@mcg1969 has given me information on the issues that I had with the cling build feature (features not being installed correctly).

I have followed his advice and was able to produce builds that now have the expected behavior wrt that feature for all the impacted packages (cling-patches, llvmdev, clangdev, cling). I have uploaded the final results of my experiment on the `cling-testing` channel. 

It would be really helpful if someone with admin privileges on conda-forge could remove the files that did not implement the features correctly. Then I will be able to push the correct version.

The files to remove would be:

1. For `llvmdev`, all those that have the `cling` and `default` strings
2. Similarly, for `clangdev`, all those that have `cling` and `default` in the build string.

**Comment by ocefpaf** [comment]
@SylvainCorlay to be on the safe side I moved them to a `broken` label for now. Please take a look if I got them all:

https://anaconda.org/conda-forge/clangdev/files?channel=broken
https://anaconda.org/conda-forge/llvmdev/files?channel=broken

Also, it would be nice if you could write something about providing `features` now that you have that experience :wink:  I am sure you were not the first to get it wrong, and won't be the last! Maybe a doc page?

**Comment by SylvainCorlay** [comment]
@ocefpaf thanks so much! I will definitely post something on features.

**Comment by ocefpaf** [comment]
> @ocefpaf thanks so much! I will definitely post something on features.

Thanks! Those docs will be a very valuable asset for `conda-forge`.

**Comment by SylvainCorlay** [comment]
@ocefpaf the `broken` tag means that I can re-upload the same file name ? (e.g. I can merge #15 ?)

**Comment by ocefpaf** [comment]
> @ocefpaf the broken label means that I can re-upload the same file name ? (e.g. I can merge #15 ?)

I would bump the build number to be higher the those in the `broken` label to be sure. (Also to document the change as an identical build would mean in-place substitution and that is bad for reproducibility, even when fixing a broken package.)

**Comment by SylvainCorlay** [comment]
OK, I will bump and merge right away. I would like to get this through before Ttravis CI backlogs come back.

**Comment by SylvainCorlay** [comment]
@ocefpaf this seems to have worked well - and we can probably delete the versions tagged as `broken`.

Note: The OS-X build of clangdev fails to upload on anaconda.org due to a token issue apparently.

**Comment by ocefpaf** [comment]
Sylvain, I am without a good internet connection for a few weeks. You'll
have better luck asking someone else. (My over the phone 3g sucks.)

**Comment by SylvainCorlay** [comment]
Thanks - no emergency anyway.

**Comment by jakirkham** [comment]
Just to be clear, everything that is broken is now labeled under "broken" or did we miss some?

**Comment by SylvainCorlay** [comment]
I don't think that we have missed anything.

This is both for clangdev and llvmdev.

**Comment by jakirkham** [comment]
Is this ok to close or was there something else we were keeping this issue open for?
