### ISSUE TITLE
Adding clang?

### ISSUE THREAD

**Issue by msarahan** [conda-forge/llvmdev-feedstock#17]
We have an intern who'd like to get started on packaging clang.  Should he start by contributing it to this recipe, or by starting a new clang staged-recipes PR?

CC @tyler-thetyrant

**Comment by SylvainCorlay** [comment]
there is already the clangdev feedstock.

**Comment by jakirkham** [comment]
Should we close and/or move this issue over to the clangdev feedstock?

**Comment by msarahan** [comment]
Thanks.  I think we should just close this issue.

**Comment by jakirkham** [comment]
Thanks Mike.

**Comment by inducer** [comment]
If you're looking for suggestions (bet you are  ;), I think something that might be valuable would be to segregate out packaging of clang/llvm by version so that (conceivably) multiple versions can be installed simultaneously.
