### ISSUE TITLE
Add VS 2008 support for llvmdev

### ISSUE THREAD

**Issue by souravsingh** [conda-forge/llvmdev-feedstock#20]
It would be useful to have Windows support, since it would help in building the llvmlite recipe and other recipes that depend of ``llvmlite``, like ``numba``.

xref https://github.com/conda-forge/staged-recipes/pull/4068

**Comment by SylvainCorlay** [comment]
llvmdev does have a windows build.

**Comment by jakirkham** [comment]
There appears to be some confusion here. So there is a Windows build of `llvmdev`, but there is not a Python 2.7 compatible build of `llvmdev` (which requires building with Visual Studio 2008). It is extremely unlikely the latter will occur as LLVM's C++ requirements are simply not matched by Visual Studio 2008.

**Comment by souravsingh** [comment]
It is strange because the builds for Windows are failing for ``llvmlite``- https://github.com/conda-forge/staged-recipes/pull/4068

**Comment by jakirkham** [comment]
There is a build issue. It isn't due to an absence of `llvmdev`. I'm not sure yet whether the cause is due to how `llvmdev` or `llvmlite` is build. Maybe this [comment]( https://github.com/conda-forge/staged-recipes/pull/4068#issuecomment-333412555 ) helps.

**Comment by jakirkham** [comment]
Hmm...just came across this [patch]( https://github.com/numba/llvmlite/blob/9088d9fc4ac18119e07c802def86d7fd73c3678d/conda-recipes/llvm-lto-static.patch ). Maybe we need to rebuild `llvmdev` with it? Maybe @sklam or @pitrou can comment further.

**Comment by jakirkham** [comment]
Have renamed the issue to make the goal a bit clearer.

**Comment by isuruf** [comment]
LLVM has dropped support for VS 2008

**Comment by jakirkham** [comment]
While it is reasonable to close this as unsupported, `defaults` does build LLVM as part of building `llvmlite` for Python 2.7. So at some point we may look at integrating their patches on this front.
