### ISSUE TITLE
Summarize Package Contents

### ISSUE THREAD

**Issue by phreed** [conda-forge/llvmdev-feedstock#231]
### Comment:

Please provide a brief summary expressing what is in the various packages.
I am developing a `clang` plugin to extract information from the AST.
In particular, I need the clang headers.
```cpp
// tag::visitor_hdr[]
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendAction.h"
#include "clang/Tooling/CommonOptionsParser.h"
#include "clang/Tooling/Tooling.h"
// end::visitor_hdr[]
```
Are these present in any of the packages?

**Comment by h-vetinari** [comment]
You're looking for `clangdev`. The "llvm" in `llvmdev` does not refer to all of the unified llvm-project repo, but only to the library portion under `/llvm`. It does not contain anything related to clang.

**Comment by phreed** [comment]
@h-vetinari  thanks. 
That said, what are in the packages?
- libllvm16
- lit
- llvm
- llvm-tools 
- llvmdev

**Comment by h-vetinari** [comment]
`llvm` is the wrapper around the versioned `libllvm16`, the actual library. `lit` is the LLVM driver for testing, `llvm-tools` is all the binaries around llvm, and `llvmdev` ties it all together (containing everything not already in one of the other outputs, notably all the headers). For more details please look at the meta.yaml here or, if you're really curious, have a look at the package [contents](https://github.com/regro/libcfgraph/blob/master/artifacts/llvmdev/conda-forge/linux-64/llvmdev-16.0.6-h5cf9203_1.json#L257).

Given that you opened https://github.com/conda-forge/clangdev-feedstock/issues/233, is there anything else you want here? If you feel like it, you can open a PR to add `about:` sections to all the outputs.

**Comment by h-vetinari** [comment]
Closing this as answered
