### ISSUE TITLE
regex_impl.h is missing on Windows

### ISSUE THREAD

**Issue by xoviat** [conda-forge/llvmdev-feedstock#29]
I can't build lldb because [this header](https://github.com/llvm-mirror/llvm/blob/master/lib/Support/regex_impl.h) is missing from the windows build.

cc @isuruf

**Comment by xoviat** [comment]
Build failure: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.19861/job/4e9ewgigdk3vwscr

**Comment by isuruf** [comment]
That's an internal header.

**Comment by xoviat** [comment]
Should be reported upstream.
