### ISSUE TITLE
Why skipping Unix + py35?

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/llvmdev-feedstock#3]
I am looking into packaging some software that depends on llvm on conda-forge.

I am wondering why the combination linux + py35 is skipped.

**Comment by inducer** [comment]
That's a red herring. LLVM/Clang is not specific to any given version of Python. This just avoids compiling the same stuff a bunch of times when the package is not different across versions (Python 2.7, 3.4, 3.5, etc.).

**Comment by SylvainCorlay** [comment]
gocha, thanks
