### ISSUE TITLE
Intel SVML patch

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/llvmdev-feedstock#36]
One of the last patches needed for Numba is a patch to `llvmdev` to use Intel's SVML library, in `icc_rt` for all transcendental functions. Would be good to get an idea of whether we are ok with this. If so, can open a PR.

cc @stuartarchibald

ref: https://github.com/AnacondaRecipes/llvmdev-feedstock/blob/4f3a2f7f36f8d3daf5fe8e739a406ccfc09a68ef/recipe/intel-svml.patch
ref: https://github.com/conda-forge/numba-feedstock/pull/7#issuecomment-385916660

**Comment by stuartarchibald** [comment]
This patch and the context can be seen here: https://github.com/numba/llvmlite/pull/326

More information on SVML is available [here](https://software.intel.com/en-us/node/524289).

The patch essentially patches LLVM 6+ such that it can be configured to generate instructions to SVML intrinsics. To make use of such instructions the SVML library needs to be present, this is available as part of the `icc_rt` package. Numba autodetects the presence of SVML and will use it if it is available (relevant PR https://github.com/numba/numba/pull/2748). One additional thing to note is that Anaconda Windows builds of NumPy depend on the `icc_rt` package and so it is present without explicitly installing it (hence noted reason for SVML test fail in here https://github.com/conda-forge/numba-feedstock/pull/7#issuecomment-385916660).

**Comment by isuruf** [comment]
Is there a issue in LLVM issue tracker?

**Comment by stuartarchibald** [comment]
Don't think so. Ping @anton-malakhov ^?

**Comment by seibert** [comment]
It appears that not having this patch in combination with Numba 0.38 produces incorrect results.  See https://github.com/conda-forge/llvmlite-feedstock/issues/5 and https://github.com/numba/numba/issues/2998.

**Comment by anton-malakhov** [comment]
Here is the upstream patch: https://reviews.llvm.org/D47188

**Comment by isuruf** [comment]
Anybody want to send a PR to this repo?

**Comment by anton-malakhov** [comment]
https://github.com/conda-forge/llvmdev-feedstock/pull/37

**Comment by jakirkham** [comment]
Rebuilding `llvmlite` now that `llvmdev` is rebuilt using PR ( https://github.com/conda-forge/llvmlite-feedstock/pull/7 ).
