### ISSUE TITLE
Co-maintainership for SylvainCorlay

### ISSUE THREAD

**Issue by inducer** [conda-forge/llvmdev-feedstock#6]
Hey @SylvainCorlay, want to co-maintain `llvmdev` and `clangdev`?

**Comment by SylvainCorlay** [comment]
Sure, I would love to!

**Comment by inducer** [comment]
Done: https://github.com/conda-forge/llvmdev-feedstock/pull/2 https://github.com/conda-forge/clangdev-feedstock/pull/4
