### ISSUE TITLE
Prevent conflicting installation with default channel's `llvm`

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/llvmdev-feedstock#60]
The `llvm` package from the default channel is in conflict with `llvmdev`. We should probably make it so that they cannot be installed at the same time.

**Comment by xhochy** [comment]
This is a bit in conflict with the `compilers` on OSX. There we need `llvm==4.0.1` for the compilers dependency to build any package.

**Comment by SylvainCorlay** [comment]
I don't think so since `llvmdev` and `clangdev` will typically be host dependencies, while llvm on OSX, which is typically pulled by `{{ compiler('cxx') }}` is a build dependency, so they should never be installed in the same environment.

**Comment by xhochy** [comment]
@SylvainCorlay When not using `conda-build` but developing inside a conda environment, I need both, the compilers and `llvmdev` installed as my package (Arrow) uses the latest LLVM as a JIT. There is have no separation of build and host dependencies.

**Comment by SylvainCorlay** [comment]
Then you have files from one package writen over files from the other.

**Comment by xhochy** [comment]
@SylvainCorlay how should we work around this issue? Add a `run_contraints` on `llvm` here and create a second `llvmdev` package that doesn't conflict with `llvm`?

**Comment by isuruf** [comment]
This is fixed now. `llvm` package is provided from this recipe and `compilers` on osx would use `llvm` from this recipe.
