### ISSUE TITLE
v9 for aarch64 / ppc64le

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/llvmdev-feedstock#80]
Hi! 

I am trying to help [build `ambertools` for PowerPC/ARM](https://github.com/conda-forge/ambertools-feedstock/issues/7), which requires `openmp`, this one [depending on `llvmdev=9`](https://github.com/conda-forge/openmp-feedstock/blob/master/recipe/meta.yaml#L52). However, [`v9` is only available in Linux64/MacOS/Windows](https://anaconda.org/conda-forge/llvmdev/files?version=9.0.0). As a result, `openmp` is not present on PPC/ARM (see [closed PR](https://github.com/conda-forge/openmp-feedstock/pull/26)).

Is there any block preventing us from having `llvmdev=9` in other archs? How should I proceed to request these builds? Thanks!

**Comment by isuruf** [comment]
See https://github.com/conda-forge/clangdev-feedstock/issues/78
